#' Retrieve Data From the U.S. Bureau Of Labor Statistics API v2
#'
#' @description
#'
#' `bls_request()`  will execute queries against the BLS API. Queries are
#' generated using one of the following query-generating functions:
#' [query_series()], [query_n_series()], [query_popular_series()],
#' [query_all_surveys()], [query_survey_info()], [query_latest_observation()].
#' The result is the "Results" block as defined in the API v2 signatures at
#' <https://www.bls.gov/developers/api_signature_v2.htm>
#'
#' @param query list generated by one of the query generating functions
#' @param api_key string, only necessary for retrieving multiple series in one
#' request, requesting calculations, or custom time frames and catalog data
#' @param user_agent string, optional
#'
#' @return a list of information returned by the API request
#'
#' @family <blsR-requests>
#'
#' @export
#'
#' @examples
#' library(blsR)
#' uer_query <- query_series('LNS14000000') #monthly unemployment rate series
#' uer_results <- bls_request(uer_query) #API response


bls_request <- function(query, api_key = NA, user_agent = 'http://github.com/groditi/blsR' ){
  ua <-  httr::user_agent(user_agent)

  #the query object should contain all it needs to make the request except
  #the BLS API key. simple requests that don't need it should be run even if
  #its missing but for complex ones with multiple series requested it should
  #inject the  key into the payload
  if(query$is_complex == FALSE){
    response <- httr::GET(query$url, ua)
    return(.process_response(response))
  }


  if('payload' %in% names(query)){
    if('series' %in% names(query$payload)){
      if(is.na(registrationkey))
        warning('api_key is required for multiple series requests.')
      query$payload[['registrationkey']] = api_key
    }
  }

  response <- httr::POST(url=query$url, ua, body=query$payload, encode="json")
  return(.process_response(response))
}

.process_response <- function(response){

  #die if the format of the response content isnt json
  if(httr::http_type(response) != "application/json"){
    stop("http request did not return json", call. = FALSE)
  }

  json_response <- jsonlite::fromJSON(
    httr::content(response, 'text'), simplifyVector=FALSE
  )

  #die if request wasn't successful
  if(json_response$status != 'REQUEST_SUCCEEDED') {
    stop(paste(json_response$message, '; '), call. = FALSE)
  }
  reuturn(json_response$Results)
}

